---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15-stretch
    working_directory: ~/jira_role

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install dependencies
          command: |
            sudo pip install -r test-requirements.txt
      - run:
          name: run tests
          command: |
            molecule test
